#!/bin/sh
set -e

if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ]; then
    if [ -x /usr/bin/deb-systemd-invoke ]; then
        deb-systemd-invoke stop 'rginx.service' >/dev/null || true
    else
        systemctl --no-reload stop rginx.service >/dev/null 2>&1 || true
    fi
fi

exit 0
