[program:rginx]
command=/usr/sbin/rginx --config /etc/rginx/rginx.ron
directory=/etc/rginx
autostart=true
autorestart=true
startsecs=3
stopsignal=QUIT
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/rginx/stdout.log
stderr_logfile=/var/log/rginx/stderr.log
stdout_logfile_maxbytes=20MB
stderr_logfile_maxbytes=20MB
stdout_logfile_backups=5
stderr_logfile_backups=5
environment=RUST_LOG="info"
