FROM rust:1.94.1-bookworm AS build

WORKDIR /src
COPY Cargo.toml Cargo.lock ./
COPY crates ./crates
RUN cargo build --release --locked -p rginx

FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates libssl3 \
    && mkdir -p /run/rginx /cache \
    && rm -rf /var/lib/apt/lists/*

COPY --from=build /src/target/release/rginx /usr/local/bin/rginx

ENTRYPOINT ["/usr/local/bin/rginx"]
