use std::fmt::Write as _;

use super::convert::{
    ConvertedCertificateBundle, ConvertedConfig, ConvertedLocation, ConvertedMatcher,
    ConvertedServer, ConvertedServerTls, ConvertedUpstream, ConvertedUpstreamTls,
    ConvertedUpstreamVerify, ConvertedVhost,
};

impl ConvertedConfig {
    pub(super) fn render(&self, source_label: &str) -> String {
        let mut out = String::new();
        let _ = writeln!(out, "// Generated by `rginx migrate-nginx` from {:?}.", source_label);
        let _ = writeln!(
            out,
            "// Review every warning before running `rginx check` or deploying the result."
        );
        if self.warnings.is_empty() {
            let _ = writeln!(out, "// No lossy migration warnings were recorded.");
        } else {
            let _ = writeln!(out, "// Migration warnings:");
            for warning in &self.warnings {
                let sanitized = warning.replace('\n', "\n//   ");
                let _ = writeln!(out, "// - {}", sanitized);
            }
        }
        let _ = writeln!(out);
        let _ = writeln!(out, "Config(");
        let _ = writeln!(out, "    runtime: RuntimeConfig(");
        let _ = writeln!(out, "        shutdown_timeout_secs: 30,");
        let _ = writeln!(out, "    ),");

        if !self.listeners.is_empty() {
            let _ = writeln!(out, "    listeners: [");
            for listener in &self.listeners {
                let _ = writeln!(out, "        ListenerConfig(");
                let _ = writeln!(out, "            name: {},", ron_string(&listener.name));
                let _ = writeln!(out, "            listen: {},", ron_string(&listener.listen));
                render_listener_tls(&mut out, "            ", listener.tls.as_ref());
                let _ = writeln!(out, "        ),");
            }
            let _ = writeln!(out, "    ],");
        }

        render_server(&mut out, &self.server);
        render_upstreams(&mut out, &self.upstreams);
        render_locations(&mut out, "    locations", &self.server.locations);
        render_vhosts(&mut out, &self.vhosts);
        let _ = writeln!(out, ")");
        out
    }
}

fn render_server(out: &mut String, server: &ConvertedServer) {
    let _ = writeln!(out, "    server: ServerConfig(");
    if let Some(listen) = &server.listen {
        let _ = writeln!(out, "        listen: {},", ron_string(listen));
    }
    if !server.server_names.is_empty() {
        let _ = writeln!(out, "        server_names: {},", ron_string_list(&server.server_names));
    }
    if let Some(limit) = server.max_request_body_bytes {
        let _ = writeln!(out, "        max_request_body_bytes: Some({limit}),");
    }
    render_server_tls(out, "        ", server.tls.as_ref());
    let _ = writeln!(out, "    ),");
}

fn render_upstreams(out: &mut String, upstreams: &[ConvertedUpstream]) {
    let _ = writeln!(out, "    upstreams: [");
    for upstream in upstreams {
        let _ = writeln!(out, "        UpstreamConfig(");
        let _ = writeln!(out, "            name: {},", ron_string(&upstream.name));
        let _ = writeln!(out, "            peers: [");
        for peer in &upstream.peers {
            let _ = writeln!(out, "                UpstreamPeerConfig(");
            let _ = writeln!(out, "                    url: {},", ron_string(&peer.url));
            if peer.weight != 1 {
                let _ = writeln!(out, "                    weight: {},", peer.weight);
            }
            if peer.backup {
                let _ = writeln!(out, "                    backup: true,");
            }
            let _ = writeln!(out, "                ),");
        }
        let _ = writeln!(out, "            ],");
        if let Some(tls) = upstream.tls.as_ref() {
            render_upstream_tls(out, "            ", tls);
        }
        if let Some(server_name) = upstream.server_name {
            let _ = writeln!(out, "            server_name: Some({server_name}),");
        }
        if let Some(server_name_override) = upstream.server_name_override.as_ref() {
            let _ = writeln!(
                out,
                "            server_name_override: Some({}),",
                ron_string(server_name_override)
            );
        }
        let _ = writeln!(out, "        ),");
    }
    let _ = writeln!(out, "    ],");
}

fn render_locations(out: &mut String, label: &str, locations: &[ConvertedLocation]) {
    let _ = writeln!(out, "{label}: [");
    for location in locations {
        let _ = writeln!(out, "        LocationConfig(");
        match &location.matcher {
            ConvertedMatcher::Exact(path) => {
                let _ = writeln!(out, "            matcher: Exact({}),", ron_string(path));
            }
            ConvertedMatcher::Prefix(path) => {
                let _ = writeln!(out, "            matcher: Prefix({}),", ron_string(path));
            }
        }
        let _ = writeln!(out, "            handler: Proxy(");
        let _ = writeln!(out, "                upstream: {},", ron_string(&location.upstream_name));
        if location.preserve_host {
            let _ = writeln!(out, "                preserve_host: Some(true),");
        }
        if !location.proxy_set_headers.is_empty() {
            let _ = writeln!(out, "                proxy_set_headers: {{");
            for (name, value) in &location.proxy_set_headers {
                let _ = writeln!(
                    out,
                    "                    {}: {},",
                    ron_string(name),
                    ron_string(value)
                );
            }
            let _ = writeln!(out, "                }},");
        }
        let _ = writeln!(out, "            ),");
        let _ = writeln!(out, "        ),");
    }
    let _ = writeln!(out, "    ],");
}

fn render_vhosts(out: &mut String, vhosts: &[ConvertedVhost]) {
    let _ = writeln!(out, "    servers: [");
    for vhost in vhosts {
        let _ = writeln!(out, "        VirtualHostConfig(");
        let _ =
            writeln!(out, "            server_names: {},", ron_string_list(&vhost.server_names));
        if let Some(tls) = vhost.tls.as_ref() {
            let _ = writeln!(out, "            tls: Some(VirtualHostTlsConfig(");
            let _ = writeln!(out, "                cert_path: {},", ron_string(&tls.cert_path));
            let _ = writeln!(out, "                key_path: {},", ron_string(&tls.key_path));
            render_additional_certificates(out, "                ", &tls.additional_certificates);
            let _ = writeln!(out, "            )),");
        }
        render_locations(out, "            locations", &vhost.locations);
        let _ = writeln!(out, "        ),");
    }
    let _ = writeln!(out, "    ],");
}

fn ron_string(value: &str) -> String {
    format!("{value:?}")
}

fn ron_string_list(values: &[String]) -> String {
    let entries = values.iter().map(|value| ron_string(value)).collect::<Vec<_>>().join(", ");
    format!("[{entries}]")
}

fn ron_enum_list(values: &[String]) -> String {
    format!("[{}]", values.join(", "))
}

fn render_listener_tls(out: &mut String, indent: &str, tls: Option<&ConvertedServerTls>) {
    if let Some(tls) = tls {
        let _ = writeln!(out, "{indent}tls: Some(ServerTlsConfig(");
        render_server_tls_body(out, &format!("{indent}    "), tls);
        let _ = writeln!(out, "{indent})),");
    }
}

fn render_server_tls(out: &mut String, indent: &str, tls: Option<&ConvertedServerTls>) {
    if let Some(tls) = tls {
        let _ = writeln!(out, "{indent}tls: Some(ServerTlsConfig(");
        render_server_tls_body(out, &format!("{indent}    "), tls);
        let _ = writeln!(out, "{indent})),");
    }
}

fn render_server_tls_body(out: &mut String, indent: &str, tls: &ConvertedServerTls) {
    let _ = writeln!(out, "{indent}cert_path: {},", ron_string(&tls.cert_path));
    let _ = writeln!(out, "{indent}key_path: {},", ron_string(&tls.key_path));
    render_additional_certificates(out, indent, &tls.additional_certificates);
    if !tls.versions.is_empty() {
        let _ = writeln!(out, "{indent}versions: Some({}),", ron_enum_list(&tls.versions));
    }
    if let Some(path) = tls.ocsp_staple_path.as_ref() {
        let _ = writeln!(out, "{indent}ocsp_staple_path: Some({}),", ron_string(path));
    }
    if let Some(enabled) = tls.session_tickets {
        let _ = writeln!(out, "{indent}session_tickets: Some({enabled}),");
    }
    if let (Some(ca_path), Some(mode)) = (&tls.client_ca_path, &tls.client_auth_mode) {
        let _ = writeln!(out, "{indent}client_auth: Some(ServerClientAuthConfig(");
        let _ = writeln!(out, "{indent}    mode: {mode},");
        let _ = writeln!(out, "{indent}    ca_cert_path: {},", ron_string(ca_path));
        if let Some(depth) = tls.client_auth_verify_depth {
            let _ = writeln!(out, "{indent}    verify_depth: Some({depth}),");
        }
        if let Some(path) = tls.client_auth_crl_path.as_ref() {
            let _ = writeln!(out, "{indent}    crl_path: Some({}),", ron_string(path));
        }
        let _ = writeln!(out, "{indent})),");
    }
}

fn render_additional_certificates(
    out: &mut String,
    indent: &str,
    additional_certificates: &[ConvertedCertificateBundle],
) {
    if additional_certificates.is_empty() {
        return;
    }

    let _ = writeln!(out, "{indent}additional_certificates: Some([");
    for bundle in additional_certificates {
        let _ = writeln!(out, "{indent}    ServerCertificateBundleConfig(");
        let _ = writeln!(out, "{indent}        cert_path: {},", ron_string(&bundle.cert_path));
        let _ = writeln!(out, "{indent}        key_path: {},", ron_string(&bundle.key_path));
        let _ = writeln!(out, "{indent}    ),");
    }
    let _ = writeln!(out, "{indent}]),");
}

fn render_upstream_tls(out: &mut String, indent: &str, tls: &ConvertedUpstreamTls) {
    let shorthand = matches!(tls.verify, ConvertedUpstreamVerify::Insecure)
        && tls.versions.is_empty()
        && tls.verify_depth.is_none()
        && tls.crl_path.is_none()
        && tls.client_cert_path.is_none()
        && tls.client_key_path.is_none();
    if shorthand {
        let _ = writeln!(out, "{indent}tls: Some(Insecure),");
        return;
    }

    let _ = writeln!(out, "{indent}tls: Some(UpstreamTlsConfig(");
    match &tls.verify {
        ConvertedUpstreamVerify::NativeRoots => {
            let _ = writeln!(out, "{indent}    verify: NativeRoots,");
        }
        ConvertedUpstreamVerify::Insecure => {
            let _ = writeln!(out, "{indent}    verify: Insecure,");
        }
        ConvertedUpstreamVerify::CustomCa(path) => {
            let _ = writeln!(out, "{indent}    verify: CustomCa(");
            let _ = writeln!(out, "{indent}        ca_cert_path: {},", ron_string(path));
            let _ = writeln!(out, "{indent}    ),");
        }
    }
    if !tls.versions.is_empty() {
        let _ = writeln!(out, "{indent}    versions: Some({}),", ron_enum_list(&tls.versions));
    }
    if let Some(depth) = tls.verify_depth {
        let _ = writeln!(out, "{indent}    verify_depth: Some({depth}),");
    }
    if let Some(path) = tls.crl_path.as_ref() {
        let _ = writeln!(out, "{indent}    crl_path: Some({}),", ron_string(path));
    }
    if let Some(path) = tls.client_cert_path.as_ref() {
        let _ = writeln!(out, "{indent}    client_cert_path: Some({}),", ron_string(path));
    }
    if let Some(path) = tls.client_key_path.as_ref() {
        let _ = writeln!(out, "{indent}    client_key_path: Some({}),", ron_string(path));
    }
    let _ = writeln!(out, "{indent})),");
}
